import numpy as np
from functools import lru_cache
from pathlib import Path
from colorwf_runner import run_color_wf, get_singlet_array, get_singlet_coefficients
from su3constants import SU3Constants

'''
/
'''


su3 = SU3Constants()

# cached wrapper for color_wf calls to avoid repeated Fortran invocations
@lru_cache(maxsize=None)
def _cached_run_color_wf(n, m, k):
    return run_color_wf(n, m, k)


def three_gluon_vertex(): # fabc
    '''
    print("f_abc:", su3.fabc)
    '''
    return 1j * su3.fabc


def four_gluon_vertex(): # 4-gluon vertex

    f = su3.fabc
    V = (np.einsum('abe,cde->abcd', f, f)
         + np.einsum('ace,bde->abcd', f, f)
         + np.einsum('ade,bce->abcd', f, f))
    return V



def gluon_contraction_by_plan(inc_n, out_n, plan, singlet_in, singlet_out):
    """
    A general gluon-to-gluon color factor contraction based on a vertex plan.
    The plan is generated by allvertices.generate_vertex_plans(inc_n, out_n).
    
    Index convention (computational):
    * incoming i-th gluon is labeled as -i
    * outgoing j-th gluon is labeled as +j
    
    Parameters:
        inc_n : int
            Number of incoming gluons.
        out_n : int
            Number of outgoing gluons.
        plan : dict
            A single plan dict from allvertices.
            Format: {'id': int, 'vertices': [{'incoming': [...], 'outgoing': [...], 'type': '...'}, ...]}
        singlet_in/singlet_out: int
            Singlet index. For getting correct d-type or f-type wavefunction from colorwf.f90. 
    
    Returns:
        dict : {'plan': plan, 'contraction_result': scalar}
    """
    
    # read incoming wf
    incoming_result = _cached_run_color_wf(0, 0, inc_n)
    gm_coeffs_inc, gm_labels_inc = get_singlet_array(incoming_result, basis="GM", singlet_index=singlet_in)
    
    incoming_wf = np.zeros((8,) * inc_n, dtype=complex)
    
    # wf reading loop (able to work for any # of gluons)
    for k in range(len(gm_labels_inc)):
        indices = []
        for i in range(inc_n):
            # follow the same label parsing pattern as the existing code
            pos = 3 + 5 * i
            idx = int(gm_labels_inc[k][pos:pos+1])
            indices.append(idx - 1)
        incoming_wf[tuple(indices)] = gm_coeffs_inc[k]
    
    # read outgoing wf
    outgoing_result = _cached_run_color_wf(0, 0, out_n)
    gm_coeffs_out, gm_labels_out = get_singlet_array(outgoing_result, basis="GM", singlet_index=singlet_out)
    
    outgoing_wf = np.zeros((8,) * out_n, dtype=complex)
    
    # wf reading loop
    for k in range(len(gm_labels_out)):
        indices = []
        for i in range(out_n):
            pos = 3 + 5 * i
            idx = int(gm_labels_out[k][pos:pos+1])
            indices.append(idx - 1)
        outgoing_wf[tuple(indices)] = gm_coeffs_out[k]
    
    # Einsum index mapping: -i for incoming, +j for outgoing
    # gid = gluon id; incoming = True/False for identifying incoming or outgoing gluon
    def idx(gid, incoming):
        if incoming:
            return gid
        else:
            return (25 + gid) 
    
    # operands list for np.einsum
    operands = []
    
    # incoming wavefunction
    inc_idx = [idx(i, True) for i in range(1, inc_n + 1)]
    operands.extend([incoming_wf, inc_idx])
    
    # outgoing wavefunction
    out_idx = [idx(j, False) for j in range(1, out_n + 1)]
    operands.extend([outgoing_wf, out_idx])
    
    # vertices
    for vertex in plan['vertices']:
        inc_ids = vertex['incoming']
        out_ids = vertex['outgoing']
        vtype = vertex['type']
        
        # Build index list for this vertex in the order: incoming first, then outgoing
        v_idx = []
        for gid in inc_ids:
            v_idx.append(idx(gid, True))
        for gid in out_ids:
            v_idx.append(idx(gid, False))
        
        if vtype == 'spectator':
            v_tensor = np.eye(8, dtype=complex)
        elif vtype == '3-gluon vertex':
            v_tensor = three_gluon_vertex()
        elif vtype == '4-gluon vertex':
            v_tensor = four_gluon_vertex()
        else:
            raise ValueError(f"Unknown vertex type: {vtype}")
        
        operands.extend([v_tensor, v_idx])
    
    # Result is a scalar
    operands.append([])
    
    # Execute contraction
    result = np.einsum(*operands)
    
    def _get_singlet_type(result, singlet_index):
        for s in result.gm_singlets:
            if s.index == singlet_index:
                return s.state_type
        return "unknown"
    
    type_in = _get_singlet_type(incoming_result, singlet_in)
    type_out = _get_singlet_type(outgoing_result, singlet_out)
    
    return {
        'plan': plan,
        'singlet_in_index': singlet_in,
        'singlet_out_index': singlet_out,
        'singlet_in_type': type_in,
        'singlet_out_type': type_out,
        'contraction_result': result
    }

'''
result = run_color_wf(n=0, m=0, k=2)
gm_coeffs, gm_labels = get_singlet_array(result, basis="GM", singlet_index=1)
print(gm_coeffs)
print(gm_labels)
num = int(gm_labels[0][3:4])
print(num)
'''